// export const jobs = [{'title': 'Market Research Associate', 'company': 'Satvik Solutions', 'location': 'Chandigarh', 'salary': '₹ 4,00,000', 'Experience': '1 year(s)', 'type': 'Fresher  Job', 'posted': '1 day ago', 'Job Link': 'https://internshala.com/job/detail/market-research-associate-job-in-multiple-locations-at-satvik-solutions1743508001'}, {'title': 'Senior Content Writer - In Office Jaipur location', 'company': 'Pinkcity Jobs', 'location': 'Jaipur', 'salary': '₹ 2,50,000 - 3,00,000', 'Experience': '₹ 4,00,000', 'type': 'Fresher  Job', 'posted': 'Today', 'Job Link': 'https://internshala.com/job/detail/senior-content-writer-job-in-jaipur-at-pinkcity-jobs1743136603'}, {'title': 'Telecaller - Night Shift', 'company': 'Rohit  Kumawat', 'location': 'Jaipur', 'salary': '₹ 2,00,000 - 2,71,000', 'Experience': '1 year(s)', 'type': 'Fresher  Job', 'posted': 'Today', 'Job Link': 'https://internshala.com/job/detail/telecaller-job-in-jaipur-at-rohit-kumawat1741678281'}, {'title': 'Customer Service Executive', 'company': 'Elevate X Solutions', 'location': 'Jaipur', 'salary': '₹ 2,00,000 - 3,50,000', 'Experience': '₹ 2,50,000 - 3,00,000', 'type': 'Fresher  Job', 'posted': '1 day ago', 'Job Link': 'https://internshala.com/job/detail/customer-service-executive-job-in-jaipur-at-elevate-x-solutions1743577251'}, {'title': 'Sales Executive', 'company': 'ADVICREST FINANCIALS', 'location': 'Pune', 'salary': '₹ 4,00,000 - 8,00,000', 'Experience': '1 year(s)', 'type': 'Fresher  Job', 'posted': 'Today', 'Job Link': 'https://internshala.com/job/detail/sales-executive-job-in-pune-at-advicrest-financials1742633057'}, {'title': 'ARCHITECT/INTERIOR DESIGNER', 'company': 'Fab Impressions Architects & Interior Designers', 'location': 'Jaipur', 'salary': '₹ 2,00,000 - 3,00,000', 'Experience': '₹ 2,00,000 - 2,71,000', 'type': 'Fresher  Job', 'posted': 'Today', 'Job Link': 'https://internshala.com/job/detail/architect-interior-designer-job-in-jaipur-at-fab-impressions-architects-interior-designers1743567811'}, {'title': 'Social Media Marketing Executive', 'company': 'Elora Fashion', 'location': 'Surat', 'salary': '₹ 2,00,000 - 2,40,000', 'Experience': '1 year(s)', 'type': 'Fresher  Job', 'posted': 'Today', 'Job Link': 'https://internshala.com/job/detail/social-media-marketing-executive-job-in-surat-at-elora-fashion1743491889'}, {'title': 'Creative Designer', 'company': 'Ace 360', 'location': 'Mumbai', 'salary': '₹ 2,00,000 - 5,00,000', 'Experience': '1 year(s)', 'type': 'Not specified', 'posted': 'Today', 'Job Link': 'https://internshala.com/job/detail/creative-designer-job-in-mumbai-at-ace-3601743595517'}, {'title': 'Business Development Executive', 'company': 'Ace 360', 'location': 'Mumbai', 'salary': '₹ 3,00,000 - 5,00,000', 'Experience': '₹ 2,00,000 - 3,00,000', 'type': 'Not specified', 'posted': '1 day ago', 'Job Link': 'https://internshala.com/job/detail/business-development-executive-job-in-mumbai-at-ace-3601743588811'}, {'title': 'ORM (Online Reputation Management', 'company': 'Credeb Advisors LLP', 'location': 'Navi Mumbai', 'salary': '₹ 3,00,000 - 3,36,000', 'Experience': '1 year(s)', 'type': 'Not specified', 'posted': '1 day ago', 'Job Link': 'https://internshala.com/job/detail/fresher-orm-online-reputation-management-job-in-navi-mumbai-at-credeb-advisors-llp1743589128'}, {'title': 'Field Sales Executive', 'company': 'Glambox Xperience & Xpositions', 'location': 'Thane', 'salary': '₹ 3,40,000 - 7,00,000', 'Experience': '₹ 2,01,000 - 2,15,000', 'type': 'Not specified', 'posted': '1 day ago', 'Job Link': 'https://internshala.com/job/detail/field-sales-executive-job-in-multiple-locations-at-glambox-xperience-xpositions1743583370'}, {'title': 'Associate Recruiter', 'company': 'Techcanvass', 'location': 'Thane', 'salary': '₹ 2,00,000 - 3,00,000', 'Experience': '0 year(s)', 'type': 'Not specified', 'posted': '1 day ago', 'Job Link': 'https://internshala.com/job/detail/associate-recruiter-job-in-multiple-locations-at-techcanvass1743583249'}, {'title': 'Video Editor', 'company': 'CyberFrat', 'location': 'Mumbai', 'salary': '₹ 3,00,000 - 4,00,000', 'Experience': '₹ 2,00,000 - 2,10,000', 'type': 'Not specified', 'posted': 'Today', 'Job Link': 'https://internshala.com/job/detail/video-editor-job-in-mumbai-at-cyberfrat1743576711'}, {'title': 'Customer Acquisition Associate', 'company': 'Cosmos Staffing Solutions', 'location': 'Gurgaon', 'salary': '₹ 2,00,000 - 3,00,000', 'Experience': '0 year(s)', 'type': 'Not specified', 'posted': '1 day ago', 'Job Link': 'https://internshala.com/job/detail/customer-acquisition-associate-job-in-gurgaon-at-cosmos-staffing-solutions1743594398'}, {'title': 'Administration Executive', 'company': 'Mudita', 'location': 'Mumbai', 'salary': '₹ 2,00,000 - 3,00,000', 'Experience': '₹ 2,00,000 - 2,40,000', 'type': 'Not specified', 'posted': '2 days ago', 'Job Link': 'https://internshala.com/job/detail/administration-executive-job-in-mumbai-at-mudita1743566578'}, {'title': 'Tele Sales Executive', 'company': 'Elevate X Solutions', 'location': 'Faridabad', 'salary': '₹ 3,10,000 - 5,00,000', 'Experience': '1 year(s)', 'type': 'Not specified', 'posted': '2 days ago', 'Job Link': 'https://internshala.com/job/detail/tele-sales-executive-job-in-multiple-locations-at-elevate-x-solutions1743576896'}, {'title': 'Digital Marketing Specialist', 'company': 'Internovo Ventures Private Limited', 'location': 'Mumbai', 'salary': '₹ 4,20,000', 'Experience': '₹ 2,16,000 - 3,00,000', 'type': 'Not specified', 'posted': '2 days ago', 'Job Link': 'https://internshala.com/job/detail/digital-marketing-specialist-job-in-mumbai-at-internovo-ventures-private-limited1743251192'}, {'title': 'Accounts Executive', 'company': 'Mudita', 'location': 'Mumbai', 'salary': '₹ 2,00,000 - 3,00,000', 'Experience': '1 year(s)', 'type': 'Not specified', 'posted': '2 days ago', 'Job Link': 'https://internshala.com/job/detail/accounts-executive-job-in-mumbai-at-mudita1743566598'}, {'title': 'Web Developer', 'company': 'Auraa Advertising Agency', 'location': 'Mumbai', 'salary': '₹ 2,10,000 - 2,36,000', 'Experience': '₹ 2,00,000 - 3,00,000', 'type': 'Not specified', 'posted': '2 days ago', 'Job Link': 'https://internshala.com/job/detail/fresher-web-developer-job-in-mumbai-at-auraa-advertising-agency1743583106'} ]


export const jobs = [
    {
      title: "Frontend",
      company: "Satvik Solutions",
      location: "Chandigarh",
      salary: "₹ 4,00,000",
      experience: "1 year(s)",
      type: "Fresher Job",
      posted: "1 day ago",
      jobLink: "https://internshala.com/job/detail/market-research-associate-job-in-multiple-locations-at-satvik-solutions1743508001",
      requirements: "User is efficent in creating a market level app.",
      skills: ["Javascript", "CSS", "Html"],
      description: "able to create a dynamic website.",
    },
    {
      title: "Senior Content Writer - In Office Jaipur location",
      company: "Pinkcity Jobs",
      location: "Jaipur",
      salary: "₹ 2,50,000 - 3,00,000",
      experience: "1 year(s)",
      type: "Fresher Job",
      posted: "Today",
      jobLink: "https://internshala.com/job/detail/senior-content-writer-job-in-jaipur-at-pinkcity-jobs1743136603",
      requirements: "Excellent writing and editing skills with knowledge of SEO.",
      skills: ["Content Writing", "SEO", "Copywriting"],
      description: "Create high-quality content for blogs, websites, and marketing materials.",
    },
    {
      title: "Telecaller - Night Shift",
      company: "Rohit Kumawat",
      location: "Jaipur",
      salary: "₹ 2,00,000 - 2,71,000",
      experience: "1 year(s)",
      type: "Fresher Job",
      posted: "Today",
      jobLink: "https://internshala.com/job/detail/telecaller-job-in-jaipur-at-rohit-kumawat1741678281",
      requirements: "Good communication skills and customer handling experience.",
      skills: ["Communication", "Customer Service", "Telecalling"],
      description: "Handle customer queries and provide effective solutions over calls.",
    },
    {
      title: "Customer Service Executive",
      company: "Elevate X Solutions",
      location: "Jaipur",
      salary: "₹ 2,00,000 - 3,50,000",
      experience: "1 year(s)",
      type: "Fresher Job",
      posted: "1 day ago",
      jobLink: "https://internshala.com/job/detail/customer-service-executive-job-in-jaipur-at-elevate-x-solutions1743577251",
      requirements: "Ability to handle customer inquiries efficiently.",
      skills: ["Customer Service", "Problem Solving", "Communication"],
      description: "Assist customers with queries and provide solutions.",
    },
    {
      title: "Sales Executive",
      company: "ADVICREST FINANCIALS",
      location: "Pune",
      salary: "₹ 4,00,000 - 8,00,000",
      experience: "1 year(s)",
      type: "Fresher Job",
      posted: "Today",
      jobLink: "https://internshala.com/job/detail/sales-executive-job-in-pune-at-advicrest-financials1742633057",
      requirements: "Strong sales and negotiation skills.",
      skills: ["Sales", "Negotiation", "Lead Generation"],
      description: "Generate leads and close deals for financial products.",
    },
    {
      title: "Web Developer",
      company: "Auraa Advertising Agency",
      location: "Mumbai",
      salary: "₹ 2,10,000 - 2,36,000",
      experience: "0 year(s)",
      type: "Fresher Job",
      posted: "2 days ago",
      jobLink: "https://internshala.com/job/detail/fresher-web-developer-job-in-mumbai-at-auraa-advertising-agency1743583106",
      requirements: "Familiarity with HTML, CSS, JavaScript, and React.",
      skills: ["HTML", "CSS", "JavaScript", "React"],
      description: "Develop and maintain web applications for various clients.",
    },
    {
      title: "Creative Designer",
      company: "Ace 360",
      location: "Mumbai",
      salary: "₹ 2,00,000 - 5,00,000",
      experience: "1 year(s)",
      type: "Not specified",
      posted: "Today",
      jobLink: "https://internshala.com/job/detail/creative-designer-job-in-mumbai-at-ace-3601743595517",
      requirements: "Proficiency in Adobe Creative Suite and graphic design tools.",
      skills: ["Adobe Photoshop", "Illustrator", "UI/UX Design"],
      description: "Create engaging designs for digital and print media.",
    },
    {
      title: "Business Development Executive",
      company: "Ace 360",
      location: "Mumbai",
      salary: "₹ 3,00,000 - 5,00,000",
      experience: "1 year(s)",
      type: "Not specified",
      posted: "1 day ago",
      jobLink: "https://internshala.com/job/detail/business-development-executive-job-in-mumbai-at-ace-3601743588811",
      requirements: "Excellent negotiation and business development skills.",
      skills: ["Business Development", "Sales", "Marketing"],
      description: "Identify and develop new business opportunities for growth.",
    },
    {
      title: "ORM (Online Reputation Management)",
      company: "Credeb Advisors LLP",
      location: "Navi Mumbai",
      salary: "₹ 3,00,000 - 3,36,000",
      experience: "1 year(s)",
      type: "Not specified",
      posted: "1 day ago",
      jobLink: "https://internshala.com/job/detail/fresher-orm-online-reputation-management-job-in-navi-mumbai-at-credeb-advisors-llp1743589128",
      requirements: "Understanding of digital marketing and reputation management.",
      skills: ["SEO", "Social Media Management", "Crisis Management"],
      description: "Monitor and improve the company's online reputation.",
    },
    {
      title: "Field Sales Executive",
      company: "Glambox Xperience & Xpositions",
      location: "Thane",
      salary: "₹ 3,40,000 - 7,00,000",
      experience: "1 year(s)",
      type: "Not specified",
      posted: "1 day ago",
      jobLink: "https://internshala.com/job/detail/field-sales-executive-job-in-multiple-locations-at-glambox-xperience-xpositions1743583370",
      requirements: "Strong field sales experience and customer engagement skills.",
      skills: ["Sales", "Lead Generation", "Client Handling"],
      description: "Develop relationships with potential clients and boost sales.",
    },
    {
      title: "Video Editor",
      company: "CyberFrat",
      location: "Mumbai",
      salary: "₹ 3,00,000 - 4,00,000",
      experience: "1 year(s)",
      type: "Not specified",
      posted: "Today",
      jobLink: "https://internshala.com/job/detail/video-editor-job-in-mumbai-at-cyberfrat1743576711",
      requirements: "Proficiency in video editing software and motion graphics.",
      skills: ["Adobe Premiere Pro", "After Effects", "Video Editing"],
      description: "Edit and enhance video content for various digital platforms.",
    }, {
        title: "Video Editor",
        company: "CyberFrat",
        location: "Mumbai",
        salary: "₹ 3,00,000 - 4,00,000",
        experience: "1 year(s)",
        type: "Not specified",
        posted: "Today",
        jobLink: "https://internshala.com/job/detail/video-editor-job-in-mumbai-at-cyberfrat1743576711",
        requirements: "Proficiency in Adobe Premiere Pro and After Effects.",
        skills: ["Adobe Premiere Pro", "After Effects", "Video Editing"],
        description: "Edit and enhance video content for digital platforms.",
      },
      {
        title: "Customer Acquisition Associate",
        company: "Cosmos Staffing Solutions",
        location: "Gurgaon",
        salary: "₹ 2,00,000 - 3,00,000",
        experience: "0 year(s)",
        type: "Not specified",
        posted: "1 day ago",
        jobLink: "https://internshala.com/job/detail/customer-acquisition-associate-job-in-gurgaon-at-cosmos-staffing-solutions1743594398",
        requirements: "Excellent communication and customer engagement skills.",
        skills: ["Customer Service", "Sales", "Lead Generation"],
        description: "Identify potential clients and convert them into customers.",
      },
      {
        title: "Administration Executive",
        company: "Mudita",
        location: "Mumbai",
        salary: "₹ 2,00,000 - 3,00,000",
        experience: "1 year(s)",
        type: "Not specified",
        posted: "2 days ago",
        jobLink: "https://internshala.com/job/detail/administration-executive-job-in-mumbai-at-mudita1743566578",
        requirements: "Strong organizational and administrative skills.",
        skills: ["Administration", "MS Office", "Time Management"],
        description: "Manage office operations and administrative tasks efficiently.",
      },
      {
        title: "Tele Sales Executive",
        company: "Elevate X Solutions",
        location: "Faridabad",
        salary: "₹ 3,10,000 - 5,00,000",
        experience: "1 year(s)",
        type: "Not specified",
        posted: "2 days ago",
        jobLink: "https://internshala.com/job/detail/tele-sales-executive-job-in-multiple-locations-at-elevate-x-solutions1743576896",
        requirements: "Experience in telesales and strong communication skills.",
        skills: ["Sales", "Telecalling", "Negotiation"],
        description: "Make outbound calls to potential clients and close sales.",
      },
      {
        title: "Digital Marketing Specialist",
        company: "Internovo Ventures Private Limited",
        location: "Mumbai",
        salary: "₹ 4,20,000",
        experience: "1 year(s)",
        type: "Not specified",
        posted: "2 days ago",
        jobLink: "https://internshala.com/job/detail/digital-marketing-specialist-job-in-mumbai-at-internovo-ventures-private-limited1743251192",
        requirements: "Proficiency in SEO, social media, and Google Ads.",
        skills: ["SEO", "Social Media Marketing", "Google Ads"],
        description: "Develop and execute digital marketing strategies for brand growth.",
      },
      {
        title: "Accounts Executive",
        company: "Mudita",
        location: "Mumbai",
        salary: "₹ 2,00,000 - 3,00,000",
        experience: "1 year(s)",
        type: "Not specified",
        posted: "2 days ago",
        jobLink: "https://internshala.com/job/detail/accounts-executive-job-in-mumbai-at-mudita1743566598",
        requirements: "Knowledge of accounting principles and financial reporting.",
        skills: ["Accounting", "Tally", "Financial Management"],
        description: "Handle financial records, accounts, and taxation matters.",
      },
      {
        title: "Web Developer",
        company: "Auraa Advertising Agency",
        location: "Mumbai",
        salary: "₹ 2,10,000 - 2,36,000",
        experience: "0 year(s)",
        type: "Not specified",
        posted: "2 days ago",
        jobLink: "https://internshala.com/job/detail/fresher-web-developer-job-in-mumbai-at-auraa-advertising-agency1743583106",
        requirements: "Familiarity with HTML, CSS, JavaScript, and React.",
        skills: ["HTML", "CSS", "JavaScript", "React"],
        description: "Develop and maintain web applications for various clients.",
      },
  ];
  